[package]
name = "xtask"
version = "0.1.0"
authors = ["DropDemBits <r3usrlnd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ungrammar = "1.6.0"
anyhow = "1.0.0"
quote = "1.0"
heck = "0.3"
xshell = "0.1"
unindent = "0.1"
