[package]
name = "toc_validate"
version = "0.1.0"
authors = ["DropDemBits <r3usrlnd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toc_reporting = { path = "../toc_reporting" }
toc_syntax = { path = "../toc_syntax" }

[dev-dependencies]
toc_parser = { path = "../toc_parser" }
expect-test = "=1.0.1"